/**
 * HWP 5.0 Tag IDs and constants.
 * Tag IDs: HWPTAG_BEGIN = 0x010 (16)
 */

export const HWPTAG_BEGIN = 0x010;

// DocInfo tags
export const HWPTAG_DOCUMENT_PROPERTIES = HWPTAG_BEGIN + 0;
export const HWPTAG_ID_MAPPINGS = HWPTAG_BEGIN + 1;
export const HWPTAG_BIN_DATA = HWPTAG_BEGIN + 2;
export const HWPTAG_FACE_NAME = HWPTAG_BEGIN + 3;
export const HWPTAG_BORDER_FILL = HWPTAG_BEGIN + 4;
export const HWPTAG_CHAR_SHAPE = HWPTAG_BEGIN + 5;
export const HWPTAG_TAB_DEF = HWPTAG_BEGIN + 6;
export const HWPTAG_NUMBERING = HWPTAG_BEGIN + 7;
export const HWPTAG_BULLET = HWPTAG_BEGIN + 8;
export const HWPTAG_PARA_SHAPE = HWPTAG_BEGIN + 9;
export const HWPTAG_STYLE = HWPTAG_BEGIN + 10;
export const HWPTAG_DOC_DATA = HWPTAG_BEGIN + 11;
export const HWPTAG_DISTRIBUTE_DOC_DATA = HWPTAG_BEGIN + 12;
export const HWPTAG_COMPATIBLE_DOCUMENT = HWPTAG_BEGIN + 14;
export const HWPTAG_LAYOUT_COMPATIBILITY = HWPTAG_BEGIN + 15;
export const HWPTAG_MEMO_SHAPE = HWPTAG_BEGIN + 76;
export const HWPTAG_FORBIDDEN_CHAR = HWPTAG_BEGIN + 78;
export const HWPTAG_TRACK_CHANGE = HWPTAG_BEGIN + 80;
export const HWPTAG_TRACK_CHANGE_AUTHOR = HWPTAG_BEGIN + 81;

// BodyText tags
export const HWPTAG_PARA_HEADER = HWPTAG_BEGIN + 50;
export const HWPTAG_PARA_TEXT = HWPTAG_BEGIN + 51;
export const HWPTAG_PARA_CHAR_SHAPE = HWPTAG_BEGIN + 52;
export const HWPTAG_PARA_LINE_SEG = HWPTAG_BEGIN + 53;
export const HWPTAG_PARA_RANGE_TAG = HWPTAG_BEGIN + 54;
export const HWPTAG_CTRL_HEADER = HWPTAG_BEGIN + 55;
export const HWPTAG_LIST_HEADER = HWPTAG_BEGIN + 56;
export const HWPTAG_PAGE_DEF = HWPTAG_BEGIN + 57;
export const HWPTAG_FOOTNOTE_SHAPE = HWPTAG_BEGIN + 58;
export const HWPTAG_PAGE_BORDER_FILL = HWPTAG_BEGIN + 59;
export const HWPTAG_SHAPE_COMPONENT = HWPTAG_BEGIN + 60;
export const HWPTAG_TABLE = HWPTAG_BEGIN + 61;
export const HWPTAG_SHAPE_COMPONENT_LINE = HWPTAG_BEGIN + 62;
export const HWPTAG_SHAPE_COMPONENT_RECTANGLE = HWPTAG_BEGIN + 63;
export const HWPTAG_SHAPE_COMPONENT_ELLIPSE = HWPTAG_BEGIN + 64;
export const HWPTAG_SHAPE_COMPONENT_ARC = HWPTAG_BEGIN + 65;
export const HWPTAG_SHAPE_COMPONENT_POLYGON = HWPTAG_BEGIN + 66;
export const HWPTAG_SHAPE_COMPONENT_CURVE = HWPTAG_BEGIN + 67;
export const HWPTAG_SHAPE_COMPONENT_OLE = HWPTAG_BEGIN + 68;
export const HWPTAG_SHAPE_COMPONENT_PICTURE = HWPTAG_BEGIN + 69;
export const HWPTAG_SHAPE_COMPONENT_CONTAINER = HWPTAG_BEGIN + 70;
export const HWPTAG_CTRL_DATA = HWPTAG_BEGIN + 71;
export const HWPTAG_EQEDIT = HWPTAG_BEGIN + 72;
export const HWPTAG_SHAPE_COMPONENT_TEXTART = HWPTAG_BEGIN + 74;
export const HWPTAG_FORM_OBJECT = HWPTAG_BEGIN + 75;
export const HWPTAG_MEMO_LIST = HWPTAG_BEGIN + 77;
export const HWPTAG_CHART_DATA = HWPTAG_BEGIN + 79;
export const HWPTAG_VIDEO_DATA = HWPTAG_BEGIN + 82;
export const HWPTAG_SHAPE_COMPONENT_UNKNOWN = HWPTAG_BEGIN + 99;

// Control character codes
export const CTRL_SECTION_COLUMN_DEF = 2;
export const CTRL_FIELD_BEGIN = 3;
export const CTRL_FIELD_END = 4;
export const CTRL_TAB = 9;
export const CTRL_LINE_BREAK = 10;
export const CTRL_DRAWING_TABLE = 11;
export const CTRL_PARA_BREAK = 13;
export const CTRL_HIDDEN_COMMENT = 15;
export const CTRL_HEADER_FOOTER = 16;
export const CTRL_FOOTNOTE_ENDNOTE = 17;
export const CTRL_AUTO_NUMBER = 18;
export const CTRL_PAGE_CTRL = 21;
export const CTRL_BOOKMARK = 22;
export const CTRL_DUTMAL = 23;

/** HWP file signature */
export const HWP_SIGNATURE = 'HWP Document File';
